language: python
cache: pip
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install -U pytest pytest-cov codecov coveralls
  - pip install tox-travis
  - pip install scrutinizer-ocular
  - pip install -e ".[all]"
script:
  - py.test -v --doctest-glob='*.md' --cov src
after_success:
  - codecov
  - coveralls
  - ocular --data-file ".coverage"
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  - provider: pypi
    edge: true
    server: https://test.pypi.org/legacy/
    user: __token__
    password:
      secure: TUHFz51F8vMfZgWTyR5QinhUkC1BdR135UtGQqPEaRUrqpV9SQKKd3NvsCyvkbxa6BFMDf2WKzV6n2j6ZqOasCY///BK/FdCXk1n73ZgPlqqthhihwsQAiDuQ2wTMDUh1mOyZZU6LNAkAV9Khm4NRHxfXksTfwkLW6Zo9THBh4uPak8/o0KA9oajuY/hTt6g+AZQkeCag8YzA61yDX/w/FUhn4eYlwThYannDW/2rgGVizRkKCXpf1F3Kr3MzSxYomfMBdYW57bC1iJMH1zoAT6ZPw3nu2v82ZXocHY+sAksvxoZJoFKF7z9CiZh0QVuv5tcbE9qVwFaXCa0j56Mc79fy1e0/6jOmC/HjCETPu5oPHii3RXIc13qkfYH/MYn6ls9yxkq6Gm8IWE0Lo2paHfUH1zdDeBheZgyRZEREYslBptIEGVMIieJobi7pLxlrxacPcV4hUbDB76sGjOjYMZvIXzXwivM0PAgdEkaLwAdkXkBOxbpei8KAryiCSOCgKMuvhbjhyiIaZdastPMUbq651ugRRZ/Jbq9IySCvaOiyt4kxbjbUSupH3GGQ2JLPricAFCxt0XsYma2a3RJUwqDtVRSDvdB5jCA6oRZ5BMyasXzDE7XWmO0tIx7olfN7jld8cRAsCy/FyR5LS5S0OdAWZ13Hz2AO219yv0/lno=
    skip_existing: true
    distributions: sdist bdist_wheel
    on:
      repo: st-bender/pyeppaurora
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION == 3.7
